//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Traits = new HashSet<Trait>();
        }
    
        public int Id { get; set; }
        public string CatName { get; set; }
    
        public virtual ICollection<Trait> Traits { get; set; }
    }
}
