//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSettings
    {
        public int Id { get; set; }
        public string Prefix { get; set; }
        public string FirstCat { get; set; }
        public string SecCat { get; set; }
        public string Suffix { get; set; }
    }
}
