//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Flies = new HashSet<Fly>();
            this.UseInstances = new HashSet<UseInstance>();
        }
    
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> Call_id { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Fly> Flies { get; set; }
        public virtual ICollection<UseInstance> UseInstances { get; set; }
    }
}
