//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trait
    {
        public Trait()
        {
            this.Flies = new HashSet<Fly>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public bool IsDominant { get; set; }
        public bool IsIncompleteDominant { get; set; }
        public bool IsLethal { get; set; }
        public byte ChromosomeNumber { get; set; }
        public double Distance { get; set; }
        public Nullable<bool> IsHeterozygous { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Fly> Flies { get; set; }
        public virtual Trait Mother { get; set; }
        public virtual Trait Father { get; set; }
    }
}
