//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseInstance
    {
        public UseInstance()
        {
            this.Flies = new HashSet<Fly>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int LabUserId { get; set; }
        public int ModuleId { get; set; }
        public string Stage { get; set; }
        public string Browser { get; set; }
        public string OS { get; set; }
        public string IP { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual LabUser LabUser { get; set; }
        public virtual Module Module { get; set; }
        public virtual ICollection<Fly> Flies { get; set; }
    }
}
